### ISSUE TITLE
Cannot find module './routes/users/'

### ISSUE THREAD

**Issue by jmarrismoboces** [m-byte/Ogar-client#2]
After running 'npm install' from the Ogar-client directory, and trying to run 'node app.js':

module.js:340
    throw err;
          ^
Error: Cannot find module './routes/users'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/joshua/Ogar-client/app.js:12:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by jmarrismoboces** [comment]
Fixed the above by commenting out the related 'require' line in app.js, and now 'node app.js' runs but immediately exits with no errors.

**Comment by MatrikMoon** [comment]
Try adding a blank "users" file in the /routes/ directory. Worked for me, but I'm still having other problems.

**Comment by schwagdawg** [comment]
Just starting looking into it. Some of the NPM dependencies have been renamed or are missing.
